spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: demo
    password: demo123
  cache:
    redis:
      time-to-live: 120
  redis:
    host: localhost
#  security:
#    user:
#      name: admin
#      password: 123456
#      roles: amdin,manager,customer

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.jetbone.app.mapper: debug

tmp.dir: ~/tmp
